import '@/styles/globals.css';
import type { AppProps } from 'next/app';
import { Provider } from 'react-redux';
import store from '../store';
import createCache from '@emotion/cache';
import { ThemeProvider, THEME_ID, createTheme } from '@mui/material/styles';
import { CacheProvider } from '@emotion/react';
import DAppBar from '@/components/app-bar';
import Head from 'next/head';

const materialTheme = createTheme();

export const muiCache = createCache({
  key: 'mui',
  prepend: true,
});

export default function App({ Component, pageProps }: AppProps) {
  return (
    <Provider store={store}>
      <CacheProvider value={muiCache}>
        <ThemeProvider theme={{ [THEME_ID]: materialTheme }}>
          <Head>
            <title>Schedule App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Component {...pageProps} />
        </ThemeProvider>
      </CacheProvider>
    </Provider>
  );
}
